title: ICLR2026
description: "ICLR 2026 Machine Learning for Remote Sensing Workshop"
baseurl: "/iclr2026"
url: "https://ml-for-rs.github.io/ml-for-remote-sensing"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


